name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: list checked out files
      run: ls -la
      
    - name: setup NodeJS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jwks-publisher:$(date +%s)
